name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: sdotnet
      run: dir  
    - name: Build with dotnet
      run: dotnet build ./myapp/myapp/ --configuration Release
    - name : dotnet publish
      run: dotnet publish ./myapp/myapp/  -c Release -o mydani
    - name : a
      uses: actions/upload-artifact@v1
      with: 
          name: dani2
          path: myapp/myapp/mydani/
