name: .NET Core

on: [push]
env:
  AZURE_WEBAPP_NAME: cloud5minsdemo   # set this to your application's name
  AZURE_GROUP_NAME: cloud5mins2
  
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: '3.1.100' # SDK Version to use.
    - name: sdotnet
      run: dir  
    - name: Build with dotnet
      run: dotnet build ./myapp/myapp/ --configuration Release
    - name : dotnet publish
      run: dotnet publish ./myapp/myapp/  -c Release -o mydani
    - name : a
      uses: actions/upload-artifact@v1
      with: 
          name: dani2
          path: ./mydani/
        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az group create -n ${{ env.AZURE_GROUP_NAME }} -l eastus 
        az group deployment create -n ghaction -g ${{ env.AZURE_GROUP_NAME }} --template-file ./myapp/azuredepoy.json


    # deploy web app using Azure credentials
    - name: 'Azure webapp deploy'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './mydani' 

    # Azure logout 
    - name: logout
      run: |
        az logout
